# See https://github.com/lowlighter/metrics
name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Required
          token: ${{ secrets.METRICS_TOKEN }}
          # Optional
          # See also https://metrics.lecoq.io/embed
          config_timezone: America/Denver
          plugin_languages: yes
          plugin_notable: yes
          plugin_notable_from: all
